"""Content engine models for the APEX funnel pipeline integrated into Graxia OS."""
import uuid
from datetime import datetime
from decimal import Decimal
from typing import Any
from uuid import UUID as UUIDType

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Integer,
    Numeric,
    String,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column
from pgvector.sqlalchemy import Vector

from .base import Base


SITE_A = "site_a"  # EN: AI Tools / Make Money
SITE_B = "site_b"  # TH: Health / Lifestyle
SITE_CHOICES = (SITE_A, SITE_B)

LANG_EN = "en"
LANG_TH = "th"
LANG_CHOICES = (LANG_EN, LANG_TH)

STATUS_PENDING = "pending"
STATUS_PROCESSING = "processing"
STATUS_DRAFT = "draft"
STATUS_REVIEW = "review"
STATUS_APPROVED = "approved"
STATUS_PUBLISHED = "published"
STATUS_ARCHIVED = "archived"
STATUS_FAILED = "failed"
STATUS_CHOICES = (STATUS_PENDING, STATUS_PROCESSING, STATUS_DRAFT, STATUS_REVIEW, STATUS_APPROVED, STATUS_PUBLISHED, STATUS_ARCHIVED, STATUS_FAILED)

CONTENT_TYPE_ARTICLE = "article"
CONTENT_TYPE_REVIEW = "review"
CONTENT_TYPE_COMPARISON = "comparison"
CONTENT_TYPE_LISTICLE = "listicle"
CONTENT_TYPE_HOWTO = "how_to"
CONTENT_TYPE_FAQ = "faq"
CONTENT_TYPE_CHOICES = (CONTENT_TYPE_ARTICLE, CONTENT_TYPE_REVIEW, CONTENT_TYPE_COMPARISON, CONTENT_TYPE_LISTICLE, CONTENT_TYPE_HOWTO, CONTENT_TYPE_FAQ)

AFFILIATE_STATUS_ACTIVE = "active"
AFFILIATE_STATUS_PAUSED = "paused"
AFFILIATE_STATUS_BROKEN = "broken"
AFFILIATE_STATUS_CHOICES = (AFFILIATE_STATUS_ACTIVE, AFFILIATE_STATUS_PAUSED, AFFILIATE_STATUS_BROKEN)


class ContentKeyword(Base):
    """Queue of keywords waiting to be turned into articles."""
    __tablename__ = "content_keywords"
    __table_args__ = (
        CheckConstraint(f"site IN {SITE_CHOICES}", name="ck_kw_site"),
        CheckConstraint(f"language IN {LANG_CHOICES}", name="ck_kw_language"),
        CheckConstraint(f"status IN {STATUS_CHOICES}", name="ck_kw_status"),
        CheckConstraint(f"content_type IN {CONTENT_TYPE_CHOICES}", name="ck_kw_content_type"),
    )

    id: Mapped[UUIDType] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    keyword: Mapped[str] = mapped_column(String(500), nullable=False)
    keyword_th: Mapped[str | None] = mapped_column(String(500))
    site: Mapped[str] = mapped_column(String(20), nullable=False, index=True)
    language: Mapped[str] = mapped_column(String(5), nullable=False, default=LANG_EN)
    content_type: Mapped[str] = mapped_column(String(20), default=CONTENT_TYPE_ARTICLE)

    # SEO metrics (populated by keyword research)
    search_volume: Mapped[int | None] = mapped_column(Integer)
    keyword_difficulty: Mapped[int | None] = mapped_column(Integer)
    cpc_usd: Mapped[Decimal | None] = mapped_column(Numeric(6, 2))
    search_intent: Mapped[str | None] = mapped_column(String(50))

    # Pipeline state
    status: Mapped[str] = mapped_column(String(20), default=STATUS_PENDING, index=True)
    priority: Mapped[int] = mapped_column(Integer, default=5)
    retry_count: Mapped[int] = mapped_column(Integer, default=0)
    error_message: Mapped[str | None] = mapped_column(Text)

    # Output linkage
    article_id: Mapped[UUIDType | None] = mapped_column(
        String(36), ForeignKey("content_articles.id", ondelete="SET NULL")
    )
    article_url: Mapped[str | None] = mapped_column(String(1024))

    created_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    processed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    published_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))


class ContentArticle(Base):
    """Published or draft articles generated by the AI pipeline."""
    __tablename__ = "content_articles"
    __table_args__ = (
        CheckConstraint(f"site IN {SITE_CHOICES}", name="ck_article_site"),
        CheckConstraint(f"language IN {LANG_CHOICES}", name="ck_article_language"),
        CheckConstraint(f"status IN {STATUS_CHOICES}", name="ck_article_status"),
        CheckConstraint(f"content_type IN {CONTENT_TYPE_CHOICES}", name="ck_article_content_type"),
    )

    id: Mapped[UUIDType] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    site: Mapped[str] = mapped_column(String(20), nullable=False, index=True)
    slug: Mapped[str] = mapped_column(String(500), nullable=False)
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    title_th: Mapped[str | None] = mapped_column(String(500))
    language: Mapped[str] = mapped_column(String(5), default=LANG_EN)
    content_type: Mapped[str] = mapped_column(String(20), default=CONTENT_TYPE_ARTICLE)

    # SEO
    meta_title: Mapped[str | None] = mapped_column(String(120))
    meta_description: Mapped[str | None] = mapped_column(String(300))
    target_keyword: Mapped[str | None] = mapped_column(String(500))
    secondary_keywords: Mapped[list[str] | None] = mapped_column(JSONB, default=list)
    schema_type: Mapped[str | None] = mapped_column(String(50), default="Article")

    # Content body (stored as MDX or plain markdown)
    body: Mapped[str] = mapped_column(Text, nullable=False)
    hero_image_url: Mapped[str | None] = mapped_column(String(1024))
    word_count: Mapped[int | None] = mapped_column(Integer)
    reading_time: Mapped[int | None] = mapped_column(Integer)

    # Affiliate products referenced in article
    affiliate_programs_used: Mapped[list[str] | None] = mapped_column(JSONB, default=list)

    # Performance (updated by scrapers/analytics sync)
    views_total: Mapped[int] = mapped_column(Integer, default=0)
    views_30d: Mapped[int] = mapped_column(Integer, default=0)
    unique_visitors: Mapped[int] = mapped_column(Integer, default=0)
    avg_time_on_page: Mapped[Decimal | None] = mapped_column(Numeric(6, 1))
    bounce_rate: Mapped[Decimal | None] = mapped_column(Numeric(5, 2))

    # Search console data (updated weekly)
    search_impressions_30d: Mapped[int] = mapped_column(Integer, default=0)
    search_clicks_30d: Mapped[int] = mapped_column(Integer, default=0)
    avg_search_position: Mapped[Decimal | None] = mapped_column(Numeric(5, 1))
    ctr: Mapped[Decimal | None] = mapped_column(Numeric(5, 4))

    # Monetization tracking
    affiliate_clicks: Mapped[int] = mapped_column(Integer, default=0)
    affiliate_revenue: Mapped[Decimal] = mapped_column(Numeric(10, 2), default=Decimal("0.00"))

    # Workflow state
    status: Mapped[str] = mapped_column(String(20), default=STATUS_DRAFT, index=True)
    needs_refresh: Mapped[bool] = mapped_column(Boolean, default=False)
    reviewed_by: Mapped[str | None] = mapped_column(String(255))
    review_notes: Mapped[str | None] = mapped_column(Text)
    published_url: Mapped[str | None] = mapped_column(String(1024))

    # Embedding for semantic duplicate detection + related articles
    # vector(1536) — compatible with text-embedding-3-small and similar 1536-dim models
    # Requires pgvector extension (enabled in 005_pgvector migration)
    # Use <=> operator for cosine similarity in is_duplicate_article()
    embedding: Mapped[list[float] | None] = mapped_column(Vector(1536))

    # Metadata
    generation_model: Mapped[str | None] = mapped_column(String(100))
    generation_tokens: Mapped[int | None] = mapped_column(Integer)
    generation_cost_usd: Mapped[Decimal | None] = mapped_column(Numeric(8, 6))
    content_hash: Mapped[str | None] = mapped_column(String(64))

    created_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    published_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    last_updated: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    __mapper_args__ = {
        "polymorphic_identity": "content_article",
    }


class AffiliateProgram(Base):
    """Affiliate program definitions and tracking."""
    __tablename__ = "affiliate_programs"
    __table_args__ = (
        CheckConstraint(f"status IN {AFFILIATE_STATUS_CHOICES}", name="ck_aff_status"),
        CheckConstraint(f"site IN {SITE_CHOICES}", name="ck_aff_site"),
    )

    id: Mapped[UUIDType] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    slug: Mapped[str] = mapped_column(String(100), unique=True, nullable=False, index=True)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    network: Mapped[str | None] = mapped_column(String(100))
    category: Mapped[str | None] = mapped_column(String(100))

    # Commission
    commission_type: Mapped[str | None] = mapped_column(String(50))  # cpa, percentage, recurring
    commission_value: Mapped[Decimal | None] = mapped_column(Numeric(8, 2))
    cookie_days: Mapped[int | None] = mapped_column(Integer)

    # URLs
    base_url: Mapped[str] = mapped_column(String(2048), nullable=False)
    dashboard_url: Mapped[str | None] = mapped_column(String(2048))
    cloaked_path: Mapped[str | None] = mapped_column(String(500))  # e.g. /go/semrush

    # Site scope
    site: Mapped[str | None] = mapped_column(String(20), index=True)

    # Status
    status: Mapped[str] = mapped_column(String(20), default=AFFILIATE_STATUS_ACTIVE)
    last_checked: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    # Performance (updated monthly)
    clicks_30d: Mapped[int] = mapped_column(Integer, default=0)
    conversions_30d: Mapped[int] = mapped_column(Integer, default=0)
    revenue_30d: Mapped[Decimal] = mapped_column(Numeric(10, 2), default=Decimal("0.00"))

    # Keywords that trigger auto-injection for this program
    trigger_keywords: Mapped[list[str] | None] = mapped_column(JSONB, default=list)
    cta_text: Mapped[str | None] = mapped_column(String(500))
    cta_text_th: Mapped[str | None] = mapped_column(String(500))

    created_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )


class AffiliateClick(Base):
    """Individual affiliate click events."""
    __tablename__ = "affiliate_clicks"

    id: Mapped[UUIDType] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    program_id: Mapped[UUIDType | None] = mapped_column(
        String(36), ForeignKey("affiliate_programs.id", ondelete="SET NULL")
    )
    program_slug: Mapped[str] = mapped_column(String(100), nullable=False, index=True)

    # Context
    article_id: Mapped[UUIDType | None] = mapped_column(
        String(36), ForeignKey("content_articles.id", ondelete="SET NULL")
    )
    article_slug: Mapped[str | None] = mapped_column(String(500))
    site: Mapped[str | None] = mapped_column(String(20), index=True)

    # Visitor
    session_id: Mapped[str | None] = mapped_column(String(255))
    country_code: Mapped[str | None] = mapped_column(String(5))
    device_type: Mapped[str | None] = mapped_column(String(20))
    referrer: Mapped[str | None] = mapped_column(String(2048))

    clicked_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )


class RevenueSnapshot(Base):
    """Daily revenue aggregation across all streams."""
    __tablename__ = "revenue_snapshots"

    id: Mapped[UUIDType] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    date: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, unique=True)

    # Revenue by stream
    affiliate_revenue: Mapped[Decimal] = mapped_column(Numeric(10, 2), default=Decimal("0.00"))
    digital_revenue: Mapped[Decimal] = mapped_column(Numeric(10, 2), default=Decimal("0.00"))
    ad_revenue: Mapped[Decimal] = mapped_column(Numeric(10, 2), default=Decimal("0.00"))
    store_revenue: Mapped[Decimal] = mapped_column(Numeric(10, 2), default=Decimal("0.00"))
    total_revenue: Mapped[Decimal] = mapped_column(Numeric(10, 2), default=Decimal("0.00"))

    # Revenue by site
    site_a_revenue: Mapped[Decimal] = mapped_column(Numeric(10, 2), default=Decimal("0.00"))
    site_b_revenue: Mapped[Decimal] = mapped_column(Numeric(10, 2), default=Decimal("0.00"))

    # Traffic
    total_pageviews: Mapped[int] = mapped_column(Integer, default=0)
    total_sessions: Mapped[int] = mapped_column(Integer, default=0)
    new_visitors: Mapped[int] = mapped_column(Integer, default=0)

    # Leads & conversions
    new_leads: Mapped[int] = mapped_column(Integer, default=0)
    total_orders: Mapped[int] = mapped_column(Integer, default=0)
    avg_order_value: Mapped[Decimal | None] = mapped_column(Numeric(8, 2))

    # Content
    articles_published: Mapped[int] = mapped_column(Integer, default=0)

    created_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
