-- Graxia Trading System — Database Schema
-- Auto-executed on first PostgreSQL container start

CREATE SCHEMA IF NOT EXISTS trading;

-- Trade log (inserted by MT5 bot via API)
CREATE TABLE IF NOT EXISTS trading.trades (
    id              BIGSERIAL PRIMARY KEY,
    symbol          VARCHAR(20) NOT NULL,
    side            VARCHAR(10) NOT NULL,
    entry_price     DECIMAL(12,5),
    exit_price      DECIMAL(12,5),
    quantity        DECIMAL(12,5),
    pnl             DECIMAL(12,5),
    entry_time      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    exit_time       TIMESTAMPTZ,
    strategy        VARCHAR(50),
    signal_id       UUID,
    model_version   VARCHAR(50),
    metadata        JSONB DEFAULT '{}',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Signal log (generated by graxia-api, consumed by MT5 bot)
CREATE TABLE IF NOT EXISTS trading.signals (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    symbol          VARCHAR(20) NOT NULL,
    action          VARCHAR(10) NOT NULL,
    confidence      DECIMAL(5,4),
    price           DECIMAL(12,5),
    strategy        VARCHAR(50),
    regime          VARCHAR(20),
    model_version   VARCHAR(50),
    features_hash   VARCHAR(64),
    received_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    processed       BOOLEAN DEFAULT FALSE,
    order_id        VARCHAR(100)
);

-- Training run metadata
CREATE TABLE IF NOT EXISTS trading.training_runs (
    id              BIGSERIAL PRIMARY KEY,
    started_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at    TIMESTAMPTZ,
    status          VARCHAR(20) DEFAULT 'running',
    model_version   VARCHAR(50),
    features_count  INTEGER,
    train_samples   INTEGER,
    val_score       DECIMAL(6,4),
    test_score      DECIMAL(6,4),
    params          JSONB,
    artifact_path   VARCHAR(500)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_trades_symbol_time ON trading.trades(symbol, entry_time DESC);
CREATE INDEX IF NOT EXISTS idx_trades_pnl ON trading.trades(pnl);
CREATE INDEX IF NOT EXISTS idx_signals_received ON trading.signals(received_at DESC);
CREATE INDEX IF NOT EXISTS idx_signals_processed ON trading.signals(processed) WHERE processed = FALSE;
CREATE INDEX IF NOT EXISTS idx_training_status ON trading.training_runs(status);
