"""Canary enums."""
from enum import Enum

class CanaryState(Enum):
    DRAFT = "DRAFT"
    PROFILE_VERIFIED = "PROFILE_VERIFIED"
    CONTRACT_VERIFIED = "CONTRACT_VERIFIED"
    MARKET_DATA_VERIFIED = "MARKET_DATA_VERIFIED"
    RISK_VERIFIED = "RISK_VERIFIED"
    PREFLIGHT_PASSED = "PREFLIGHT_PASSED"
    AWAITING_HUMAN_APPROVAL = "AWAITING_HUMAN_APPROVAL"
    APPROVED = "APPROVED"
    EXECUTION_MUTEX_HELD = "EXECUTION_MUTEX_HELD"
    SUBMITTING = "SUBMITTING"
    SUBMISSION_RECEIPT_RECORDED = "SUBMISSION_RECEIPT_RECORDED"
    POSITION_RECONCILING = "POSITION_RECONCILING"
    POSITION_OPEN_CONFIRMED = "POSITION_OPEN_CONFIRMED"
    EXIT_REQUESTED = "EXIT_REQUESTED"
    EXIT_RECONCILING = "EXIT_RECONCILING"
    CLOSED_CONFIRMED = "CLOSED_CONFIRMED"
    SEALED = "SEALED"
    # Terminal / blocked states
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    KILLED = "KILLED"
    SUBMISSION_UNKNOWN = "SUBMISSION_UNKNOWN"
    RECONCILIATION_FAILED = "RECONCILIATION_FAILED"
    RECOVERY_REQUIRED = "RECOVERY_REQUIRED"

class CanaryActor(Enum):
    SYSTEM = "SYSTEM"
    OPERATOR = "OPERATOR"
    BROKER = "BROKER"
