"""Phase 4 — Margin Call & Forced Liquidation Simulator.

Models real-world margin mechanics that can amplify drawdowns:
- Margin utilization tracking per position
- Margin call triggers when equity drops below maintenance threshold
- Forced liquidation at discounted prices (10-15% worse than market)
- Feedback loop: forced selling → price impact → more margin calls

Research (Wikipedia + institutional practice):
- Maintenance margin typically 25-50% (Reg T = 50% initial, 25% maintenance)
- Forced liquidation discount: 10-15% below fair value
- Margin call delay: T+1 to T+2 depending on broker
- Liquidity spirals: bid-ask spreads widen 5-10x during margin calls
"""

from __future__ import annotations

from dataclasses import dataclass, field
from decimal import Decimal


@dataclass
class MarginConfig:
    """Margin simulation configuration."""

    initial_margin_pct: float = 0.50  # Reg T: 50% initial margin
    maintenance_margin_pct: float = 0.25  # 25% maintenance margin
    forced_liquidation_discount: float = 0.10  # 10% discount on forced liquidation
    margin_call_delay_bars: int = 2  # T+2 delay before forced liquidation
    warning_threshold_pct: float = 0.80  # Warn when margin utilization > 80%
    max_leverage: float = 4.0  # Maximum allowed leverage


@dataclass
class MarginState:
    """Current margin state for a position or portfolio."""

    total_equity: Decimal = Decimal("0")
    used_margin: Decimal = Decimal("0")
    available_margin: Decimal = Decimal("0")
    margin_utilization: float = 0.0  # used_margin / total_equity
    margin_call_pending: bool = False
    margin_call_bar: int = 0  # Bar index when margin call was triggered
    forced_liquidation_executed: bool = False


@dataclass
class MarginEvent:
    """Event generated by margin simulation."""

    event_type: str  # "WARNING", "MARGIN_CALL", "FORCED_LIQUIDATION"
    bar_index: int
    equity: Decimal
    margin_utilization: float
    position_symbol: str = ""
    liquidation_discount: float = 0.0
    message: str = ""


class MarginSimulator:
    """Simulates margin mechanics in backtesting.

    Tracks margin utilization, triggers margin calls, and executes
    forced liquidations with realistic discounts and delays.
    """

    def __init__(self, config: MarginConfig | None = None):
        self.config = config or MarginConfig()
        self._pending_calls: dict[str, int] = {}  # symbol -> bar_index when call triggered
        # Phase 4: Cap events list to prevent unbounded memory growth
        self._events: list[MarginEvent] = []
        self._max_events: int = 1000

    @property
    def events(self) -> list[MarginEvent]:
        """Return accumulated margin events."""
        return list(self._events)

    def calculate_margin_state(
        self,
        positions: list[dict],
        account_equity: Decimal,
        current_bar: int = 0,
    ) -> MarginState:
        """Calculate current margin state.

        Args:
            positions: List of position dicts with keys:
                - symbol, entry_price, quantity, side, current_price
            account_equity: Current account equity (balance + unrealized P&L)
            current_bar: Current bar index for delay tracking

        Returns:
            MarginState with current margin metrics
        """
        if account_equity <= 0:
            return MarginState(
                total_equity=account_equity,
                used_margin=Decimal("0"),
                available_margin=Decimal("0"),
                margin_utilization=1.0,
            )

        # Calculate used margin (initial margin requirement)
        used_margin = Decimal("0")
        for pos in positions:
            entry = pos.get("entry_price", Decimal("0"))
            qty = pos.get("quantity", Decimal("0"))
            if entry > 0 and qty > 0:
                notional = entry * qty
                margin = notional * Decimal(str(self.config.initial_margin_pct))
                used_margin += margin

        available = account_equity - used_margin
        utilization = float(used_margin / account_equity) if account_equity > 0 else 1.0

        return MarginState(
            total_equity=account_equity,
            used_margin=used_margin,
            available_margin=max(Decimal("0"), available),
            margin_utilization=round(utilization, 4),
        )

    def check_margin(
        self,
        positions: list[dict],
        account_equity: Decimal,
        current_bar: int,
        current_prices: dict[str, Decimal] | None = None,
    ) -> list[MarginEvent]:
        """Check margin status and generate events.

        Args:
            positions: Current open positions
            account_equity: Current equity
            current_bar: Current bar index
            current_prices: Optional current prices for mark-to-market

        Returns:
            List of MarginEvent if any triggered
        """
        events = []

        if not positions or account_equity <= 0:
            return events

        state = self.calculate_margin_state(positions, account_equity, current_bar)

        # Mark-to-market adjustment if prices provided
        if current_prices:
            unrealized = Decimal("0")
            for pos in positions:
                sym = pos.get("symbol", "")
                price = current_prices.get(sym, pos.get("entry_price", Decimal("0")))
                qty = pos.get("quantity", Decimal("0"))
                entry = pos.get("entry_price", Decimal("0"))
                side = pos.get("side", "LONG")
                if side == "LONG":
                    unrealized += (price - entry) * qty
                else:
                    unrealized += (entry - price) * qty
            state.total_equity = account_equity + unrealized
            if state.total_equity > 0:
                state.margin_utilization = float(state.used_margin / state.total_equity)

        # Warning threshold
        if state.margin_utilization > self.config.warning_threshold_pct:
            events.append(MarginEvent(
                event_type="WARNING",
                bar_index=current_bar,
                equity=state.total_equity,
                margin_utilization=state.margin_utilization,
                message=f"Margin utilization {state.margin_utilization:.1%} > {self.config.warning_threshold_pct:.0%} warning threshold",
            ))

        # Margin call trigger (equity < maintenance margin)
        maintenance_equity = state.used_margin * Decimal(str(self.config.maintenance_margin_pct))
        if state.total_equity < maintenance_equity and state.used_margin > 0:
            # Check if we already have a pending call
            for pos in positions:
                sym = pos.get("symbol", "")
                if sym not in self._pending_calls:
                    self._pending_calls[sym] = current_bar
                    events.append(MarginEvent(
                        event_type="MARGIN_CALL",
                        bar_index=current_bar,
                        equity=state.total_equity,
                        margin_utilization=state.margin_utilization,
                        position_symbol=sym,
                        message=f"MARGIN CALL: equity {state.total_equity} < maintenance {maintenance_equity}",
                    ))

        # Forced liquidation (after delay)
        for sym, call_bar in list(self._pending_calls.items()):
            if current_bar - call_bar >= self.config.margin_call_delay_bars:
                events.append(MarginEvent(
                    event_type="FORCED_LIQUIDATION",
                    bar_index=current_bar,
                    equity=state.total_equity,
                    margin_utilization=state.margin_utilization,
                    position_symbol=sym,
                    liquidation_discount=self.config.forced_liquidation_discount,
                    message=f"FORCED LIQUIDATION: {sym} at {self.config.forced_liquidation_discount:.0%} discount",
                ))
                del self._pending_calls[sym]

        self._events.extend(events)
        # Phase 4: Cap events list to prevent unbounded memory
        if len(self._events) > self._max_events:
            self._events = self._events[-self._max_events:]
        return events

    def apply_forced_liquidation(
        self,
        position: dict,
        current_price: Decimal,
    ) -> tuple[Decimal, Decimal]:
        """Apply forced liquidation with discount.

        Args:
            position: Position dict with entry_price, quantity, side
            current_price: Current market price

        Returns:
            (exit_price, pnl) after forced liquidation discount
        """
        discount = Decimal(str(self.config.forced_liquidation_discount))
        qty = position.get("quantity", Decimal("0"))
        side = position.get("side", "LONG")
        entry = position.get("entry_price", Decimal("0"))

        if side == "LONG":
            # Forced sell at discounted price
            exit_price = current_price * (Decimal("1") - discount)
            pnl = (exit_price - entry) * qty
        else:
            # Forced buy at inflated price
            exit_price = current_price * (Decimal("1") + discount)
            pnl = (entry - exit_price) * qty

        return exit_price, pnl

    def reset(self):
        """Reset state for a new backtest run."""
        self._pending_calls.clear()
        self._events.clear()
