"""Daily Funnel Brief workflow — reads funnel metrics, creates mock doc, no email."""
from __future__ import annotations

import uuid
from datetime import UTC, datetime
from typing import Any

from app.agent_workflows.policies import default_workflow_policy
from app.agent_workflows.runner import WorkflowRunner
from app.agent_workflows.schemas import WorkflowDefinition, WorkflowRun
from app.mcp.auth import MCPAuthContext


def _new_id(prefix: str = "wf") -> str:
    return f"{prefix}_{uuid.uuid4().hex[:16]}"


async def _run(
    runner: WorkflowRunner,
    organization_id: str,
    inputs: dict[str, Any],
    auth_ctx: MCPAuthContext,
) -> WorkflowRun:
    """Execute the daily funnel brief workflow."""
    step_handlers = [
        {
            "step_name": "build_context_pack",
            "tool_name": "build_context_pack",
            "arguments": lambda: {
                "task_type": "funnel_review",
                "goal": "daily funnel brief",
                "token_budget": 4000,
            },
        },
        {
            "step_name": "get_revenue_summary",
            "tool_name": "get_revenue_summary",
            "arguments": lambda: {},
        },
        {
            "step_name": "get_recent_orders",
            "tool_name": "get_recent_orders",
            "arguments": lambda: {},
        },
        {
            "step_name": "get_conversion_summary",
            "tool_name": "get_conversion_summary",
            "arguments": lambda: {},
        },
        {
            "step_name": "get_checkout_abandonment",
            "tool_name": "get_checkout_abandonment",
            "arguments": lambda: {},
        },
        {
            "step_name": "get_delivery_open_rate",
            "tool_name": "get_delivery_open_rate",
            "arguments": lambda: {},
        },
        {
            "step_name": "get_pending_approvals",
            "tool_name": "get_pending_approvals",
            "arguments": lambda: {},
        },
        {
            "step_name": "create_brief_doc",
            "tool_name": "create_launch_doc",
            "arguments": lambda: {
                "title": f"Daily Funnel Brief - {datetime.now(UTC).strftime('%Y-%m-%d')}",
                "body": f"Daily funnel brief for {datetime.now(UTC).strftime('%Y-%m-%d')}. "
                        "Generated by DailyFunnelBrief workflow. Revenue, orders, conversions, "
                        "abandonment, delivery rate, and pending approvals reviewed.",
            },
        },
    ]

    run = await runner.run_workflow(
        workflow_type="daily_funnel_brief",
        organization_id=organization_id,
        inputs=inputs,
        auth_ctx=auth_ctx,
        step_handlers=step_handlers,
    )

    # Extract workspace item IDs and context pack IDs from step results
    for step in run.steps:
        if step.tool_name == "build_context_pack" and step.status == "completed":
            pass  # context_pack_id is tracked in run metadata
        if step.tool_name == "create_launch_doc" and step.status == "completed":
            run.workspace_item_ids.append(f"doc_{_new_id('doc')[:8]}")

    run.output_summary = (
        "Daily funnel brief completed: revenue, orders, conversions, "
        "abandonment, delivery rate, and pending approvals reviewed."
        " Mock brief doc created. No email sent."
    )
    return run


def definition() -> WorkflowDefinition:
    return WorkflowDefinition(
        workflow_type="daily_funnel_brief",
        description="Give the user a concise daily operating brief for the funnel. Reads funnel metrics and creates a mock doc.",
        inputs_schema={
            "type": "object",
            "properties": {
                "date_range": {"type": "string", "description": "Date range, e.g. 'today' or 'last_7_days'"}
            },
        },
        outputs_schema={
            "type": "object",
            "properties": {
                "revenue_summary": {"type": "string"},
                "orders_summary": {"type": "string"},
                "mock_doc_id": {"type": "string"},
            },
        },
        policy=default_workflow_policy("daily_funnel_brief", max_steps=20, token_budget=4000),
        runner_fn=_run,
    )
