"""Add multi-agent orchestration models

Revision ID: 4497f1eedc0b
Revises: 005
Create Date: 2026-04-23 00:35:56.601345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4497f1eedc0b'
down_revision: Union[str, None] = '005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('sender', sa.String(length=50), nullable=False),
    sa.Column('receiver', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_messages_session_id'), 'agent_messages', ['session_id'], unique=False)
    op.create_table('agent_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('assigned_to', sa.String(length=50), nullable=False),
    sa.Column('assigned_by', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('idx_projects_owner_id', table_name='projects')
    op.drop_index('idx_projects_status', table_name='projects')
    op.drop_table('projects')
    op.drop_index('idx_task_comments_task_id_created_at', table_name='task_comments')
    op.drop_table('task_comments')
    op.drop_table('task_updates')
    op.drop_table('notifications')
    op.drop_index('idx_project_weekly_updates_project_id', table_name='project_weekly_updates')
    op.drop_table('project_weekly_updates')
    op.drop_table('trello_config')
    op.drop_index('idx_task_audit_logs_task_id_created_at', table_name='task_audit_logs')
    op.drop_table('task_audit_logs')
    op.drop_index('idx_users_line_user_id', table_name='users_legacy_incompatible')
    op.drop_table('users_legacy_incompatible')
    op.drop_table('task_assignments')
    op.drop_table('departments')
    op.drop_index('idx_blockers_project_id', table_name='blockers')
    op.drop_index('idx_blockers_task_id', table_name='blockers')
    op.drop_table('blockers')
    op.drop_table('task_types')
    op.drop_table('trello_user_mappings')
    op.drop_index('idx_trello_sync_logs_task_id_created_at', table_name='trello_sync_logs')
    op.drop_table('trello_sync_logs')
    op.drop_index('idx_tasks_project_id', table_name='tasks')
    op.drop_index('idx_tasks_tags', table_name='tasks', postgresql_using='gin')
    op.drop_table('tasks')
    op.drop_index('idx_task_checklists_checked_by', table_name='task_checklists')
    op.drop_table('task_checklists')
    op.drop_table('trello_status_mappings')
    op.drop_index('idx_project_milestones_project_id', table_name='project_milestones')
    op.drop_table('project_milestones')
    op.drop_table('trello_card_mappings')
    op.drop_index('idx_task_priority', table_name='assistant_tasks')
    op.create_index('idx_task_priority', 'assistant_tasks', ['priority'], unique=False, postgresql_ops={'priority': 'DESC'})
    op.drop_index('idx_task_status_priority', table_name='assistant_tasks')
    op.create_index('idx_task_status_priority', 'assistant_tasks', ['status', 'priority'], unique=False, postgresql_ops={'priority': 'DESC'})
    op.drop_index('idx_email_message_received', table_name='email_messages')
    op.create_index('idx_email_message_received', 'email_messages', ['received_at'], unique=False, postgresql_ops={'received_at': 'DESC'})
    op.drop_index('idx_email_last_message', table_name='email_threads')
    op.create_index('idx_email_last_message', 'email_threads', ['last_message_at'], unique=False, postgresql_ops={'last_message_at': 'DESC'})
    op.drop_index('idx_email_priority', table_name='email_threads')
    op.create_index('idx_email_priority', 'email_threads', ['priority'], unique=False, postgresql_ops={'priority': 'DESC'})
    op.drop_index('knowledge_embedding_hnsw', table_name='knowledge_items', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index('idx_network_interaction_at', table_name='network_interactions')
    op.create_index('idx_network_interaction_at', 'network_interactions', ['interaction_at'], unique=False, postgresql_ops={'interaction_at': 'DESC'})
    op.drop_index('idx_openclaw_created', table_name='openclaw_usage')
    op.create_index('idx_openclaw_created', 'openclaw_usage', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.drop_index('idx_scraper_started', table_name='scraper_runs')
    op.create_index('idx_scraper_started', 'scraper_runs', ['started_at'], unique=False, postgresql_ops={'started_at': 'DESC'})
    op.drop_constraint('users_email_key1', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key1', 'users', ['email'])
    op.drop_index('idx_scraper_started', table_name='scraper_runs', postgresql_ops={'started_at': 'DESC'})
    op.create_index('idx_scraper_started', 'scraper_runs', [sa.text('started_at DESC')], unique=False)
    op.drop_index('idx_openclaw_created', table_name='openclaw_usage', postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_openclaw_created', 'openclaw_usage', [sa.text('created_at DESC')], unique=False)
    op.drop_index('idx_network_interaction_at', table_name='network_interactions', postgresql_ops={'interaction_at': 'DESC'})
    op.create_index('idx_network_interaction_at', 'network_interactions', [sa.text('interaction_at DESC')], unique=False)
    op.create_index('knowledge_embedding_hnsw', 'knowledge_items', ['embedding'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index('idx_email_priority', table_name='email_threads', postgresql_ops={'priority': 'DESC'})
    op.create_index('idx_email_priority', 'email_threads', [sa.text('priority DESC')], unique=False)
    op.drop_index('idx_email_last_message', table_name='email_threads', postgresql_ops={'last_message_at': 'DESC'})
    op.create_index('idx_email_last_message', 'email_threads', [sa.text('last_message_at DESC')], unique=False)
    op.drop_index('idx_email_message_received', table_name='email_messages', postgresql_ops={'received_at': 'DESC'})
    op.create_index('idx_email_message_received', 'email_messages', [sa.text('received_at DESC')], unique=False)
    op.drop_index('idx_task_status_priority', table_name='assistant_tasks', postgresql_ops={'priority': 'DESC'})
    op.create_index('idx_task_status_priority', 'assistant_tasks', ['status', sa.text('priority DESC')], unique=False)
    op.drop_index('idx_task_priority', table_name='assistant_tasks', postgresql_ops={'priority': 'DESC'})
    op.create_index('idx_task_priority', 'assistant_tasks', [sa.text('priority DESC')], unique=False)
    op.create_table('trello_card_mappings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('trello_card_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('trello_card_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='trello_card_mappings_task_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='trello_card_mappings_pkey'),
    sa.UniqueConstraint('task_id', name='trello_card_mappings_task_id_key')
    )
    op.create_table('project_milestones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=True),
    sa.CheckConstraint("status = ANY (ARRAY['pending'::text, 'completed'::text])", name='project_milestones_status_check'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='project_milestones_project_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='project_milestones_pkey')
    )
    op.create_index('idx_project_milestones_project_id', 'project_milestones', ['project_id'], unique=False)
    op.create_table('trello_status_mappings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('trello_list_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('trello_list_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='trello_status_mappings_pkey'),
    sa.UniqueConstraint('status', name='trello_status_mappings_status_key')
    )
    op.create_table('task_checklists',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_checked', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('checked_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('checked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['checked_by'], ['users_legacy_incompatible.id'], name='task_checklists_checked_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='task_checklists_task_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='task_checklists_pkey')
    )
    op.create_index('idx_task_checklists_checked_by', 'task_checklists', ['checked_by'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('tasks_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('task_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.TEXT(), server_default=sa.text("'medium'::text"), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=True),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('progress', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=True),
    sa.CheckConstraint("priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'urgent'::text])", name='tasks_priority_check'),
    sa.CheckConstraint("status = ANY (ARRAY['pending'::text, 'in_progress'::text, 'completed'::text, 'cancelled'::text])", name='tasks_status_check'),
    sa.ForeignKeyConstraint(['created_by'], ['users_legacy_incompatible.id'], name='tasks_created_by_fkey'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='tasks_project_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_type_id'], ['task_types.id'], name='tasks_task_type_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tasks_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_tasks_tags', 'tasks', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('idx_tasks_project_id', 'tasks', ['project_id'], unique=False)
    op.create_table('trello_sync_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('trello_card_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('retry_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='trello_sync_logs_task_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='trello_sync_logs_pkey')
    )
    op.create_index('idx_trello_sync_logs_task_id_created_at', 'trello_sync_logs', ['task_id', sa.text('created_at DESC')], unique=False)
    op.create_table('trello_user_mappings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('trello_member_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('trello_username', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_legacy_incompatible.id'], name='trello_user_mappings_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='trello_user_mappings_pkey'),
    sa.UniqueConstraint('user_id', name='trello_user_mappings_user_id_key')
    )
    op.create_table('task_types',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('task_types_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='task_types_pkey'),
    sa.UniqueConstraint('name', name='task_types_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('blockers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('reported_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'active'::text"), autoincrement=False, nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=True),
    sa.CheckConstraint("status = ANY (ARRAY['active'::text, 'resolved'::text])", name='blockers_status_check'),
    sa.CheckConstraint('project_id IS NOT NULL OR task_id IS NOT NULL', name='blockers_target_check'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='blockers_project_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_by'], ['users_legacy_incompatible.id'], name='blockers_reported_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='blockers_task_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='blockers_pkey')
    )
    op.create_index('idx_blockers_task_id', 'blockers', ['task_id'], unique=False)
    op.create_index('idx_blockers_project_id', 'blockers', ['project_id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('departments_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='departments_pkey'),
    sa.UniqueConstraint('name', name='departments_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('task_assignments',
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assigned_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='task_assignments_task_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users_legacy_incompatible.id'], name='task_assignments_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'user_id', name='task_assignments_pkey')
    )
    op.create_table('users_legacy_incompatible',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('username', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('password', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('auth_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('role', sa.TEXT(), server_default=sa.text("'staff'::text"), autoincrement=False, nullable=True),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('position', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('line_user_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.CheckConstraint("role = ANY (ARRAY['admin'::text, 'staff'::text])", name='users_role_check'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name='users_department_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('auth_id', name='users_auth_id_key'),
    sa.UniqueConstraint('email', name='users_email_key'),
    sa.UniqueConstraint('username', name='users_username_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_users_line_user_id', 'users_legacy_incompatible', ['line_user_id'], unique=False)
    op.create_table('task_audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('old_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='task_audit_logs_task_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users_legacy_incompatible.id'], name='task_audit_logs_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='task_audit_logs_pkey')
    )
    op.create_index('idx_task_audit_logs_task_id_created_at', 'task_audit_logs', ['task_id', 'created_at'], unique=False)
    op.create_table('trello_config',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('api_key_encrypted', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token_encrypted', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('board_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('board_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('enable_auto_sync', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('enable_two_way_sync', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('webhook_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('webhook_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint('id = 1', name='single_row'),
    sa.PrimaryKeyConstraint('id', name='trello_config_pkey')
    )
    op.create_table('project_weekly_updates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('week_start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('completed_this_week', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('planned_next_week', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('current_blockers', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('risk_level', sa.TEXT(), server_default=sa.text("'low'::text"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=True),
    sa.CheckConstraint("risk_level = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text])", name='project_weekly_updates_risk_level_check'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='project_weekly_updates_project_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users_legacy_incompatible.id'], name='project_weekly_updates_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='project_weekly_updates_pkey')
    )
    op.create_index('idx_project_weekly_updates_project_id', 'project_weekly_updates', ['project_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), server_default=sa.text("'info'::text"), autoincrement=False, nullable=True),
    sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_legacy_incompatible.id'], name='notifications_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='notifications_pkey')
    )
    op.create_table('task_updates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('update_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('progress', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('attachment_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='task_updates_task_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users_legacy_incompatible.id'], name='task_updates_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='task_updates_pkey')
    )
    op.create_table('task_comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='task_comments_task_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users_legacy_incompatible.id'], name='task_comments_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='task_comments_pkey')
    )
    op.create_index('idx_task_comments_task_id_created_at', 'task_comments', ['task_id', 'created_at'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'planning'::text"), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), server_default=sa.text("'new_dev'::text"), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('deadline', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('launch_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('client_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('repo_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('domain_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('demo_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('design_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=True),
    sa.Column('color', sa.TEXT(), server_default=sa.text("'#5A5A40'::text"), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=True),
    sa.CheckConstraint("status = ANY (ARRAY['planning'::text, 'developing'::text, 'testing'::text, 'launched'::text, 'maintenance'::text, 'on_hold'::text, 'cancelled'::text])", name='projects_status_check'),
    sa.CheckConstraint("type = ANY (ARRAY['new_dev'::text, 'maintenance'::text, 'bug_fix'::text, 'support'::text])", name='projects_type_check'),
    sa.ForeignKeyConstraint(['owner_id'], ['users_legacy_incompatible.id'], name='projects_owner_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='projects_pkey')
    )
    op.create_index('idx_projects_status', 'projects', ['status'], unique=False)
    op.create_index('idx_projects_owner_id', 'projects', ['owner_id'], unique=False)
    op.drop_table('agent_tasks')
    op.drop_index(op.f('ix_agent_messages_session_id'), table_name='agent_messages')
    op.drop_table('agent_messages')
    # ### end Alembic commands ###
