flowchart LR
    %% File Dependency Graph

    f0b644b51dc2["__init__"]
    aae8f5be1b58["db"]
    6f601f42c99a["app"]

    %% Dependencies
    6f601f42c99a --> aae8f5be1b58
    f0b644b51dc2 --> 6f601f42c99a