#!/bin/bash
# Generate secure secrets for production deployment

echo "# Generated secrets - $(date)"
echo "# Add these to your .env file"
echo ""
echo "# Security Keys"
echo "SECRET_KEY=$(openssl rand -base64 64 | tr -d '\n')"
echo "ENCRYPTION_KEY=$(openssl rand -base64 32 | tr -d '\n')"
echo "CSRF_SECRET=$(openssl rand -base64 32 | tr -d '\n')"
echo "API_KEY=$(openssl rand -base64 32 | tr -d '\n')"
echo ""
echo "# Database Passwords"
echo "POSTGRES_PASSWORD=$(openssl rand -base64 32 | tr -d '\n')"
echo "REDIS_PASSWORD=$(openssl rand -base64 32 | tr -d '\n')"
echo ""
echo "# Admin Credentials"
echo "ADMIN_DEFAULT_PASSWORD=$(openssl rand -base64 24 | tr -d '\n')"
echo "GRAFANA_ADMIN_PASSWORD=$(openssl rand -base64 24 | tr -d '\n')"
echo "N8N_PASSWORD=$(openssl rand -base64 24 | tr -d '\n')"
echo ""
echo "# Service Credentials"
echo "FLOWER_BASIC_AUTH=admin:$(openssl rand -base64 24 | tr -d '\n')"
echo "ALERTMANAGER_WEBHOOK_TOKEN=$(openssl rand -base64 32 | tr -d '\n')"
echo ""
echo "# Backup Encryption"
echo "BACKUP_ENCRYPTION_PUBLIC_KEY=$(openssl rand -base64 32 | tr -d '\n')"
