"""Central source-of-truth for DSR n_trials (multiple-testing correction).

Replaces the 5 separate hardcoded/scoped sources documented in WS-C of
the live-trading readiness plan:

  1. validation/pipeline/config.py        — hardcoded dsr_n_trials=50
  2. validation/overfitting_detector.py    — hardcoded n_trials=150 (docstring)
  3. validation/strategy_validator.py      — max(len(param_grid), 5)
  4. validation/search_budget.py           — in-session per-strategy count
  5. scripts/compute_deflated_sharpe.py    — reads reconciliation file  ← CORRECT

All in-process DSR callers MUST obtain n_trials from this module.

The canonical source is reports/trial_count_reconciliation_<date>.json,
generated by scripts/reconcile_trial_ledger.py.  The key field is
``total_n_for_multiple_testing``.

Usage::

    from validation.n_trials import get_reconciled_n_trials

    n = get_reconciled_n_trials()  # -> int (currently 1050)

    # Optionally pass an explicit reconciliation file:
    n = get_reconciled_n_trials("reports/trial_count_reconciliation_20260720.json")

    # For environments where the reconciliation file hasn't been generated yet
    # but you need a conservative floor:
    n = get_reconciled_n_trials(minimum=50)  # floor of 50
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Default reconciliation file (committed to repo, generated by
# scripts/reconcile_trial_ledger.py)
# ---------------------------------------------------------------------------
_DEFAULT_RECONCILIATION = Path(__file__).resolve().parent.parent / "reports" / "trial_count_reconciliation_20260720.json"

# Current reconciled value (commit this file as the authoritative artifact)
_CURRENT_RECONCILED_N = 1050


def _read_reconciliation_file(
    path: Path | str | None = None,
) -> int | None:
    """Read the ``total_n_for_multiple_testing`` from a reconciliation JSON.

    Returns ``None`` if the file cannot be read or parsed.
    """
    source = Path(path) if path else _DEFAULT_RECONCILIATION
    try:
        data = json.loads(source.read_text(encoding="utf-8"))
    except (FileNotFoundError, json.JSONDecodeError, OSError) as exc:
        logger.warning("Cannot read trial reconciliation file %s: %s", source, exc)
        return None

    # Ordered preference for known keys (same order as compute_deflated_sharpe.py)
    for key in (
        "total_n_for_multiple_testing",
        "reconciled_trial_count",
        "total_trials",
        "n_trials",
    ):
        if key in data:
            return int(data[key])

    logger.warning("Reconciliation file %s missing expected N key", source)
    return None


def get_reconciled_n_trials(
    reconciliation_path: Path | str | None = None,
    minimum: int = 2,
) -> int:
    """Return the authoritative N for DSR multiple-testing correction.

    Resolution order:
      1. Explicit ``reconciliation_path``, if provided and readable.
      2. The default committed reconciliation file.
      3. Fallback: the hard-coded ``_CURRENT_RECONCILED_N`` constant
         (kept in sync with the committed file).

    The returned value is always >= ``minimum`` (default 2, since DSR
    requires N >= 2).

    Parameters
    ----------
    reconciliation_path : Path | str | None
        Override the default reconciliation file path.
    minimum : int
        Floor on the returned N (default 2, DSR minimum).

    Returns
    -------
    int
        The reconciled total number of trials tested across the project.
    """
    n = _read_reconciliation_file(reconciliation_path)
    if n is None:
        n = _CURRENT_RECONCILED_N
        logger.info("Using hard-coded reconciled N=%d (reconciliation file unavailable)", n)

    return max(n, minimum)
